### ISSUE TITLE
Suggestion: add multi instance support and move to the official group

### ISSUE THREAD

**Issue by ngot** [zcong1993/egg-lru#2]
# Problem

In the real world, we always need more than one cache instance.It is reasonable to add multi-instance support the lru-cache plugin to avoid importing another lru module by hand.

# Solution

By use the egg's [manual](https://eggjs.org/zh-cn/advanced/plugin.html#%E5%85%A8%E5%B1%80%E5%AE%9E%E4%BE%8B%E6%8F%92%E4%BB%B6%E7%9A%84%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5)

# Move to official group 

then I can also participate in the development.

**Comment by zcong1993** [comment]
fixed #3 , and updated docs
